### ISSUE TITLE
用老哥整理的梯子两年了，是到说再见的时候了吗？

### ISSUE THREAD

**Issue by Acer-bdog** [Memory2314/VMesslinks#4]

**Comment by Memory2314** [comment]
还能用 你可以自己fork过去 我不想开action了 你fork过去改下action照样用

**Comment by Memory2314** [comment]
action重新开了 刚刚又提交了下代码
[fe25803](https://github.com/Memory2314/VMesslinks/commit/fe25803b8e1f9925a037cf04455e5ff960ed3464)

**Comment by Memory2314** [comment]
新实现
[4466341](https://github.com/Memory2314/VMesslinks/commit/4466341ca6882f922b41efc0e0c286dee6f5dc77)
